name: Build and test
on:
  # Manual trigger
  workflow_dispatch:

  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  build_and_test:
    name: Build and test the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository in file system
        uses: actions/checkout@v2

      - name: Set up Node 12
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
